[build]
  command = "npm run build"
  publish = "dist"

[build.secrets_scan_omit_keys]
  keys = ["VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
